# netlify.toml

[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "frontend/dist"
  node_version = "18"

[context.production.environment]
  # API URL for frontend
  VITE_API_BASE_URL = "https://healthcare-data-apis.onrender.com/"

# SPA routing redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
